### ISSUE TITLE
Get the app to read from a database 

### ISSUE THREAD

**Issue by martinchooooooo** [Feggla/bball_website#1]
There are a frew part to this task that you should follow in order:

## Part 1

Get you app to talk to a postgres DB locally on your mac. 

Firstly you'll have to install Postgres on your laptop, which is pretty straight forward with Homebrew. [Try this guide](https://www.sqlshack.com/setting-up-a-postgresql-database-on-mac). Along the way you'll learn some separate tools that let you see your database, one that I use for example is [Postico](https://eggerapps.at/postico/v1.php).

## Part 2

Now that you have Postgres locally, you'll need to connect to it from your app. [This seems to be a good guide](https://astaxie.gitbooks.io/build-web-application-with-golang/content/en/05.4.html) for how to connect to postgres. 

## Part 3 - The actual part

Actually implement Part 2. What I want is a table in your database called `User` where you store an `id` and a `username` field. The field should be a varchar where you will store the users of your website. 
- Add a new endpoint to your webapp for `/users` that lists all the users in your app. 
- If you want to add new users, just use your sql client (i.e something like Postico) to add and edit them

**Comment by Feggla** [comment]
Issue closed with [7f8cee9](https://github.com/Feggla/bball_website/commit/7f8cee96cd075e4b60f045b666b0df734b3002d9)
